import Head from 'next/head'
import {
  HeroBanner,
  Footer
} from '../components/index'
import { client } from '../lib/client'

export default function Home({ products, bannerData }) {
  return (
    <div>
      <Head>
        <title>Ecommerce-Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen">

        <HeroBanner heroBanner={bannerData.length && bannerData[0]}/>

        <div className="flex flex-col items-center m-20">
          <h2 className="mb-4 text-6xl font-bold text-cyan-900">Best Selling Products</h2>
          <p className="text-lg font-thin">Speakers of many variations</p>
        </div>

        <div className="flex justify-center">
          {products?.map((product) => product.name)}
        </div>

        <Footer />

      </div>
      
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]'
  const products = await client.fetch(query)

  const bannerQuery = '*[_type == "banner"]'
  const bannerData = await client.fetch(bannerQuery)

  return {
    props: { products, bannerData }
  }
}
