import Head from 'next/head'
import {
  HeroBanner,
  Footer
} from '../components/index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecommerce-Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen">

        <HeroBanner />

        <div className="flex flex-col items-center m-20">
          <h2 className="text-6xl font-bold text-cyan-900 mb-4">Best Selling Products</h2>
          <p className="font-thin text-lg">Speakers of many variations</p>
        </div>

        <div className="flex justify-center">
          {['Product 1', 'Product 2', 'Product 3'].map((product) => product)}
        </div>

        <Footer />

      </div>
      
    </div>
  )
}
